# Generated by Django 4.1.3 on 2023-01-12 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_name', models.CharField(max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/banners')),
                ('content', models.CharField(max_length=100, null=True)),
                ('selected', models.CharField(max_length=100, null=True)),
                ('validity_upto', models.DateField(null=True)),
                ('banner_id', models.CharField(default=0, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
