# Generated by Django 4.1.3 on 2023-01-12 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0006_category_discount_product_category_offer_and_more'),
        ('User_Section', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='banner_id',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='content',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='selected',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='validity_upto',
        ),
        migrations.AddField(
            model_name='banner',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='category.product'),
            preserve_default=False,
        ),
    ]
