# Generated by Django 4.1.3 on 2022-12-05 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='blocked',
            field=models.BooleanField(default=False),
        ),
    ]
