# Generated by Django 4.1.3 on 2022-12-19 09:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_otp_profile_uid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=30)),
                ('address_1', models.CharField(max_length=100)),
                ('pincode', models.IntegerField()),
                ('district', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('landmark', models.CharField(max_length=20, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
