# Generated by Django 4.1.3 on 2022-12-19 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_guestcart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Guestcart',
        ),
    ]
