# Generated by Django 4.1.3 on 2023-01-07 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_delete_guestcart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='variant_id',
            field=models.CharField(blank=True, default=0, max_length=100, null=True),
        ),
    ]
